on: [push]

name: CI

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    name: Rust project
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            target/release/debugit*
  gather_builds:
    name: Gather Build outputs
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Download ubuntu binary
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest
      - name: Download windows binary
        uses: actions/download-artifact@v3
        with:
          name: windows-latest
      - name: Download windows binary
        uses: actions/download-artifact@v3
        with:
          name: macos-latest
      - name: Print the final result
        shell: bash
        run: |
          ls -alR


